version: '3.6'

services:
  app1:
    build:
      context: ./app1
      dockerfile: Dockerfile
    volumes:
      - './app1:/usr/src/app'
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - PYTHONUNBUFFERED=1
      - APP_CONFIG=project.configs.DevelopmentConfig
    networks:
      - apps
      - dbs

  app2:
    build:
      context: ./app2
      dockerfile: Dockerfile
    volumes:
      - './app2:/usr/src/app'
    ports:
      - 80:5000
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - PYTHONUNBUFFERED=1
    networks:
      - apps
      - other

  postgres-db:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - dbs

networks:
  apps:
    name: apps-network
  other:
    name: other-network
  dbs:
    name: dbs-network
