version: '3.6'

services:
  app1:
    build:
      context: ./app1
      dockerfile: Dockerfile
    volumes:
      - './app1:/usr/src/app'
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - PYTHONUNBUFFERED=1
    networks:
      - apps

  app2:
    build:
      context: ./app2
      dockerfile: Dockerfile
    volumes:
      - './app2:/usr/src/app'
    ports:
      - 8000:5000
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - PYTHONUNBUFFERED=1
    networks:
      - apps
      - other

networks:
  apps:
    name: apps-network
  other:
    name: other-network
