version: '3.7'
services:
  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: example.com # set to fqdn of host
    ports:
      - 19999:19999
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    environment:
      - NETDATA_CLAIM_TOKEN=tKkNHQkHUJU4qb76OfeqxlOOK8TeUtnZ9uxCP96itnZnz63tiQiNc-dOMo4jFqWWjKnXyssG8Stt1IZBI9I5Z1bfN7bq4Fk3Tr5Ux_s79i8rBYthSnIic54fUlcou-NSTbqylLI
      - NETDATA_CLAIM_URL=https://app.netdata.cloud
      - NETDATA_CLAIM_ROOMS=1905ecb6-1765-4ea4-b254-101e95016747
    volumes:
      netdataconfig:
      netdatalib:
      netdatacache: